---
kind: pipeline
name: arm64_gcc_make

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    CC: gcc
    COMMON_FLAGS: 'DYNAMIC_ARCH=1 TARGET=ARMV8 NUM_THREADS=32'
  commands: 
    - apt-get update -q
    - apt-get install wget -y -q
    - wget https://github.com/flang-compiler/llvm/suites/1969908451/artifacts/39135837
    # - bash .github/workflows/drone.sh
