---
kind: pipeline
name: arm64_gcc_make

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:18.04
  environment:
    GITHUB_TOKEN:
      from_secret: DRONE_GITHUB_TOKEN
    OTHER_GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    CC: gcc
    COMMON_FLAGS: 'DYNAMIC_ARCH=1 TARGET=ARMV8 NUM_THREADS=32'
  commands: 
    # - bash -c "printenv"
    - bash .github/workflows/drone.sh
