language: c

cache:
  directories:
    - $HOME/.conda/pkgs
    - $HOME/miniconda/pkgs

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -u -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge --force
  - conda update -q conda

  - conda create -q -n test-environment
        flang-meta 
        llvmdev
        clangdev
        openmp
        cmake

  - source activate test-environment
  - conda info -a
  
  # For testing
  - pip install lit

script:
  - mkdir -p build
  - cd build
  - cmake -DFLANG_INCLUDE_TESTS=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_Fortran_COMPILER=flang ..
  - make -j4
  
  - cp lib/* $HOME/miniconda/envs/test-environment/lib
  - cp bin/* $HOME/miniconda/envs/test-environment/bin
  
  - make check-flang

notifications:
    email: false
